apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 5000  # Flask's internal port
      nodePort: 30080
