name: CI/CD/T

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
    paths:
      - 'flask-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: 'docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app-image:latest ./flask-app'

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-image:latest

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k3s/deployment.yaml
          kubectl apply -f k3s/service.yaml
